# Generated by Django 6.0.3 on 2026-09-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBodyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'body regions',
                'db_table': 'exercise_body_region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'exercise_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'forces',
                'db_table': 'exercise_force',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'levels',
                'db_table': 'exercise_level',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'mechanics',
                'db_table': 'exercise_mechanic',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=128, unique=True)),
                ('english', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'muscle',
                'ordering': ['original'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Muscle Group',
                'verbose_name_plural': 'Muscle Groups',
                'db_table': 'muscle_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body_region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mfj.exercisebodyregion')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mfj.exercisecategory')),
                ('force', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mfj.exerciseforce')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mfj.exerciselevel')),
                ('mechanic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mfj.exercisemechanic')),
                ('target_muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mfj.muscle')),
                ('muscle_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mfj.musclegroup')),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='ExerciseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='mfj.exercise')),
            ],
            options={
                'db_table': 'exercise_instruction',
            },
        ),
        migrations.CreateModel(
            name='MuscleGroupMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfj.muscle')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfj.musclegroup')),
            ],
            options={
                'db_table': 'muscle_group_muscle',
                'unique_together': {('muscle', 'muscle_group')},
            },
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='muscles',
            field=models.ManyToManyField(related_name='groups', through='mfj.MuscleGroupMuscle', to='mfj.muscle'),
        ),
        migrations.CreateModel(
            name='MuscleHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='mfj.muscle')),
            ],
            options={
                'verbose_name': 'Muscle Head',
                'verbose_name_plural': 'Muscle Heads',
                'db_table': 'muscle_head',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_muscles', to='mfj.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_exercises', to='mfj.muscle')),
            ],
            options={
                'db_table': 'exercise_muscle',
                'ordering': ['role'],
                'unique_together': {('exercise', 'muscle')},
            },
        ),
    ]
