# Generated by Django 6.0.3 on 2026-09-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfj', '0002_alter_exercisebodyregion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisebodyregion',
            options={'ordering': ['id'], 'verbose_name_plural': 'Body Regions'},
        ),
    ]
