# Generated by Django 6.0.3 on 2026-09-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutexercise_execution_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='execution_order',
        ),
    ]
