# Generated by Django 6.0.3 on 2026-03-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programexercise',
            table='program_exercises',
        ),
        migrations.AlterModelTable(
            name='programsection',
            table='program_sections',
        ),
    ]
