# Generated by Django 6.0.3 on 2026-05-17 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(
                max_length=255, unique=True, verbose_name='Program description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(
                max_length=128, unique=True, verbose_name='Program title'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='load',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
