# Generated by Django 6.0.3 on 2026-03-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_user_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
