# Generated by Django 6.0.3 on 2026-03-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_programexercise_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programexercise',
            table='programs_program_exercises',
        ),
        migrations.AlterModelTable(
            name='programsection',
            table='programs_program_sections',
        ),
    ]
