# Generated by Django 6.0.3 on 2026-03-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programexercise',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programsection'),
        ),
        migrations.AlterField(
            model_name='programsection',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
    ]
