# Generated by Django 6.0.3 on 2026-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_programexercise_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration_weeks',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='reps',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='rest_seconds',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='rpe',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='sets',
            field=models.SmallIntegerField(),
        ),
    ]
