# Generated by Django 6.0.3 on 2026-03-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_programexercise_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programsection',
            old_name='program',
            new_name='program_id',
        ),
    ]
