# Generated by Django 6.0.3 on 2026-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_rename_program_programsection_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexercise',
            name='load',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
