# Generated by Django 6.0.3 on 2026-03-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_programexercise_load'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programexercise',
            old_name='section',
            new_name='section_id',
        ),
    ]
