# Generated by Django 6.0.3 on 2026-05-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muscles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBodyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'exercise_body_region',
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'exercise_category',
            },
        ),
        migrations.CreateModel(
            name='ExerciseForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'exercise_force',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'levels',
                'db_table': 'exercise_level',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'exercise_mechanic',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_muscle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='muscles.muscle')),
                ('body_region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisebodyregion')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisecategory')),
                ('force', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exerciseforce')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exerciselevel')),
                ('mechanic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisemechanic')),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_muscles', to='exercises.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_exercises', to='muscles.muscle')),
            ],
            options={
                'db_table': 'exercise_muscle',
                'ordering': ['role', 'order'],
                'unique_together': {('exercise', 'muscle')},
            },
        ),
    ]
