# Generated by Django 6.0.3 on 2026-05-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisebodyregion',
            options={'verbose_name_plural': 'body regions'},
        ),
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='exerciseforce',
            options={'verbose_name_plural': 'forces'},
        ),
        migrations.AlterModelOptions(
            name='exercisemechanic',
            options={'verbose_name_plural': 'mechanics'},
        ),
    ]
