# Generated by Django 6.0.3 on 2026-04-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_difficulty_remove_exercise_title_exercise_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'ordering': ['name'], 'verbose_name_plural': 'difficulties'},
        ),
    ]
