# Generated by Django 6.0.3 on 2026-05-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercisebodyregion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisemuscle',
            options={'ordering': ['role']},
        ),
        migrations.RemoveField(
            model_name='exercisemuscle',
            name='order',
        ),
    ]
