# Generated by Django 6.0.3 on 2026-04-21 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_difficulty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(default=datetime.datetime(2026, 4, 21, 12, 14, 20, 933711, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
