# Generated by Django 6.0.3 on 2026-05-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_muscle_group'),
        ('muscles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='target_muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='muscles.muscle'),
        ),
        migrations.CreateModel(
            name='ExerciseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='exercises.exercise')),
            ],
            options={
                'db_table': 'exercise_instruction',
            },
        ),
    ]
