# Generated by Django 6.0.3 on 2026-05-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exercise_target_muscle_exerciseinstruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstruction',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
