# Generated by Django 6.0.3 on 2026-05-13 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisebodyregion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisebodyregion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
