# Generated by Django 6.0.3 on 2026-05-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_exercisecategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisebodyregion',
            options={'ordering': ['id'], 'verbose_name_plural': 'body regions'},
        ),
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={'ordering': ['id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='exerciseforce',
            options={'ordering': ['id'], 'verbose_name_plural': 'forces'},
        ),
        migrations.AlterModelOptions(
            name='exercisemechanic',
            options={'ordering': ['id'], 'verbose_name_plural': 'mechanics'},
        ),
    ]
