# Generated by Django 6.0.3 on 2026-05-08 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=128, unique=True)),
                ('english', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'muscle',
                'ordering': ['original'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Muscle Group',
                'verbose_name_plural': 'Muscle Groups',
                'db_table': 'muscle_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroupMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muscles.muscle')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muscles.musclegroup')),
            ],
            options={
                'db_table': 'muscle_group_muscle',
                'unique_together': {('muscle', 'muscle_group')},
            },
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='muscles',
            field=models.ManyToManyField(related_name='groups', through='muscles.MuscleGroupMuscle', to='muscles.muscle'),
        ),
    ]
