# Generated by Django 6.0.3 on 2026-05-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='muscles.muscle')),
            ],
            options={
                'verbose_name': 'Muscle Head',
                'verbose_name_plural': 'Muscle Heads',
                'db_table': 'muscle_head',
                'ordering': ['name'],
            },
        ),
    ]
