# Generated by Django 6.0.3 on 2026-04-30 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muscle',
            old_name='name',
            new_name='english',
        ),
        migrations.RemoveField(
            model_name='muscle',
            name='description',
        ),
        migrations.AddField(
            model_name='muscle',
            name='original',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
