# Generated by Django 6.0.3 on 2026-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0002_musclehead'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musclegroupmuscle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musclehead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
