# Generated by Django 6.0.3 on 2026-04-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0002_rename_name_muscle_english_remove_muscle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='english',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
