# Generated by Django 6.0.3 on 2026-05-17 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0003_muscle_updated_at_musclegroup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroupmuscle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
