# Generated by Django 6.0.3 on 2026-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0003_alter_muscle_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='english',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
