# Generated by Django 6.0.3 on 2026-04-30 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0004_alter_muscle_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='english',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
