# Generated by Django 6.0.3 on 2026-04-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0005_alter_muscle_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='english',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
